import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Card from "../components/card/card";
import NumberInput from "../components/number-input";
import styles from "../styles/form.module.css";

export default function Form() {
  const [numberOfDoors, setNumberOfDoors] = useState(3);
  const [prizedDoor, setPrizedDoor] = useState(1);

  return (
    <div className={styles.form}>
      <Head>
        <title>Monty Hall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Card bgColor={"#c0392c"}>
          <h1>Monty Hall</h1>
        </Card>
        <Card>
          <NumberInput
            text="Quantidade de portas"
            value={numberOfDoors}
            onChange={(newNumberOfDoors) => setNumberOfDoors(newNumberOfDoors)}
          />
        </Card>
      </div>
      <div>
        <Card>
          <NumberInput
            text="Porta premiada"
            value={prizedDoor}
            onChange={(newPrizedDoor) => setPrizedDoor(newPrizedDoor)}
          />
        </Card>
        <Card bgColor={"#28a085"}>
          <Link href={`/game/${numberOfDoors}/${prizedDoor}`} passHref>
            <h2 className={styles.title}>Iniciar</h2>
          </Link>
        </Card>
      </div>
    </div>
  );
}
